---
dataset:
 train:
  - /work/submit/lavezzo/debug/
 validation:
  - /work/submit/lavezzo/debug/val/
 test:
  - /work/submit/lavezzo/debug/val/

model_pref:
 hidden_dim: 16
 out_dim: 1

training_pref:
 lambda_disco: 2
 batch_size_train: 512
 batch_size_validation: 1024
 max_epochs: 50
 learning_rate: 0.001
 step_size: 20
 gamma: 0.5

evaluation_pref:
 batch_size: 50
 names_classes:
  - 'SUEP'
  - 'QCD'
 workers: 0
